/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Base64;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author ADMIN
 */
public class Registeration extends javax.swing.JFrame {
   Connection conn;
   PreparedStatement param;
   ResultSet rs; 

   public Registeration() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nametf = new javax.swing.JTextField();
        usernametf = new javax.swing.JTextField();
        emailtf = new javax.swing.JTextField();
        passtf = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cpasstf = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(824, 568));
        setPreferredSize(new java.awt.Dimension(824, 568));
        getContentPane().setLayout(null);

        nametf.setBorder(null);
        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });
        getContentPane().add(nametf);
        nametf.setBounds(363, 230, 171, 18);

        usernametf.setBorder(null);
        getContentPane().add(usernametf);
        usernametf.setBounds(363, 279, 171, 18);

        emailtf.setBorder(null);
        getContentPane().add(emailtf);
        emailtf.setBounds(363, 328, 171, 18);

        passtf.setBorder(null);
        getContentPane().add(passtf);
        passtf.setBounds(363, 377, 171, 18);

        jButton1.setText("Register ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(153, 498, 139, 29);

        jButton2.setText("How to Use");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 498, 139, 29);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(567, 498, 137, 29);

        cpasstf.setBorder(null);
        getContentPane().add(cpasstf);
        cpasstf.setBounds(362, 426, 171, 18);

        jLabel7.setIcon(new javax.swing.ImageIcon("G:\\Netbeans Project\\IsProject\\src\\isproject\\Hacknet Registration.png")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 820, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
          String name=nametf.getText();
          String username=usernametf.getText();
          String email=emailtf.getText();
          String password=passtf.getText();
          String confirm_password=cpasstf.getText();
          
          
          if((nametf.getText().equals("")) || usernametf.getText().equals("") || emailtf.getText().equals("") || passtf.getText().equals("") || cpasstf.getText().equals("")){
            JOptionPane.showMessageDialog(null,"<html><font face='Times New Roman' size='5' color='black'>Incomplete data");
          }
          else if(password.equals(confirm_password)&& emailvalidation(email)){
            try{
                String sql="INSERT INTO users(name,username,email,password,publickey,privatekey)VALUES(?,?,?,?,?,?)";
                conn = Connection_DB.makeConnection();
                param=conn.prepareStatement(sql);
                //param.setInt(1,0);
                param.setString(1,name);
                param.setString(2,username);
                param.setString(3,email);
                param.setString(4,password);
                Methods.initKeys();
                System.out.println(Methods.getPublic()+"\n"+Methods.getPrivate());
                param.setString(5,Base64.getEncoder().encodeToString(Methods.getPublic().getEncoded()));
                param.setString(6,Base64.getEncoder().encodeToString(Methods.getPrivate().getEncoded()));
                JOptionPane.showMessageDialog(null, "Please wait for the \"Registeration Successful message\"");
                Methods.sendEmail(Methods.convertPublicToString(Methods.getPublic()),Methods.convertPrivateToString(Methods.getPrivate()), email);
                System.out.println("Email Sent");
                int  i=param.executeUpdate();
                if(i>0){
                      JOptionPane.showMessageDialog(null,"<html><font face='Times New Roman' size='5' color='black'>Registered Successfully.");
                      this.setVisible(false);
                      new Login().setVisible(true);
                      nametf.setText("");
                      usernametf.setText("");
                      emailtf.setText("");
                      passtf.setText("");
                      cpasstf.setText("");

                }
                else
                     JOptionPane.showMessageDialog(null,"<html><font face='Times New Roman' size='5' color='black'>Data is not inserted");

            }
            catch(Exception e){
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null,"<html><font face='Times New Roman' size='5' color='black'>Incomplete data");
            }
          }
          else
              JOptionPane.showMessageDialog(null, "Data Format not valid.");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new HowToUse().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                
               UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registeration().setVisible(true);
            }
        });
    }
      
    //check email validation
   public boolean emailvalidation(String email){
          email=emailtf.getText();
          boolean status=false;
          
          Pattern pattern = Pattern.compile ("([a-zA-Z0-9_\\-\\.]+)@((\\[a-z]{1,3}\\.[a-z]"+ "{1,3}\\.[a-z]{1,3}\\.)|(([a-zA-Z\\-]+\\.)+))"+ "([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)",
                                              Pattern.MULTILINE);

          Matcher m=pattern.matcher(email);
          boolean b=m.matches();

          if(emailtf.getText().length()>0)
                     if(m.matches()){
                            status=true;
                      }
                     else{
                            status=false;
                     }
          return status;
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cpasstf;
    private javax.swing.JTextField emailtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nametf;
    private javax.swing.JPasswordField passtf;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
