/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package isproject;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author ADMIN
 */
public class SymmetricEncryption extends javax.swing.JFrame {
    String secretKey ="";
    public SymmetricEncryption() {
        initComponents();
        //populateUsers();
        setLocationRelativeTo(null);
        setResizable(false);
    }
     public void populateUsers(){
        Connection con = Connection_DB.makeConnection();
        try {
            ResultSet rst = con.createStatement().executeQuery("select name from users");
            users.addItem("Select receiver's name");
            while(rst.next()){
                users.addItem(rst.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Encryption.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
      public ImageIcon resizeImage(String path){
        BufferedImage img = null;
        Image dimg=null;
        try {
            img = ImageIO.read(new File(path)); 
            dimg = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),
            Image.SCALE_SMOOTH);
            
        }
        catch (IOException e) {
            e.printStackTrace();
        }
        finally{
            return new ImageIcon(dimg);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ptext = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        etext = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        shareKey = new javax.swing.JButton();
        key = new javax.swing.JTextField();
        users = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 580));
        setPreferredSize(new java.awt.Dimension(1000, 580));
        getContentPane().setLayout(null);

        ptext.setBackground(new java.awt.Color(199, 208, 216));
        ptext.setColumns(20);
        ptext.setFont(new java.awt.Font("Ebrima", 0, 13)); // NOI18N
        ptext.setRows(5);
        jScrollPane1.setViewportView(ptext);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 270, 370, 160);

        etext.setBackground(new java.awt.Color(199, 208, 216));
        etext.setColumns(20);
        etext.setFont(new java.awt.Font("Ebrima", 0, 13)); // NOI18N
        etext.setForeground(new java.awt.Color(255, 0, 0));
        etext.setRows(5);
        jScrollPane2.setViewportView(etext);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(540, 270, 370, 160);

        jButton1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton1.setText("Encrypt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(235, 457, 151, 38);

        shareKey.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        shareKey.setText("Share Key");
        shareKey.setEnabled(false);
        shareKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareKeyActionPerformed(evt);
            }
        });
        getContentPane().add(shareKey);
        shareKey.setBounds(425, 457, 151, 38);

        key.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        getContentPane().add(key);
        key.setBounds(94, 206, 811, 23);

        users.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        getContentPane().add(users);
        users.setBounds(380, 128, 187, 21);

        jButton2.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton2.setText("Dashboard");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(617, 457, 150, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\Netbeans Project\\IsProject\\src\\isproject\\4.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1010, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    shareKey.setEnabled(true);
    secretKey = key.getText();
    String plain = ptext.getText(); 
    String encryptedString = Methods.encrypt(plain, secretKey) ;
    etext.setText(encryptedString);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void shareKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareKeyActionPerformed
        try {
            String name = users.getSelectedItem().toString();
            Connection con = Connection_DB.makeConnection();
            ResultSet rst = con.createStatement().executeQuery("Select email from users where name='"+name+"'");
            rst.next();
            String email = rst.getString(1);
            JOptionPane.showMessageDialog(null, "Please wait. As key transfer process is completed ,you will be notified.");
            Methods.sendEmail2(secretKey, email);
            JOptionPane.showMessageDialog(null, "Secret key has been sent to your receiver through secure hacknet mailing system.");
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(SymmetricEncryption.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_shareKeyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Dashboard().setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SymmetricEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SymmetricEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SymmetricEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SymmetricEncryption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SymmetricEncryption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea etext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField key;
    private javax.swing.JTextArea ptext;
    private javax.swing.JButton shareKey;
    private javax.swing.JComboBox<String> users;
    // End of variables declaration//GEN-END:variables
}
